Split tree directory = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/Split_Tree_nwk_files
Perl script directory = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script
A Tree/B Tree directory = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/Split_Tree_nwk_files/
Original unsplit tree (already fixed length) = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/Unsplit_Main_Tree/250phyl_subtree.nwk
A Tree output file = >Dibamidae_Hele_Dicro_A_Tree.nwk
Splitter species = Dibamidae
Overlap species 1 = Heleophryn
Overlap species 2 = Dicrogloss
Outgroup species = Polyodonti
Nodes to delete = 
B Tree output file = >Dibamidae_Hele_Dicro_B_Tree.nwk
B Tree first species = Cryptobran
Nul check directory = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/nul_check
SeqGen Sequences location = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/765_gene_sequences_all
Nul output file = nul_characters
Split genes directory = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/split_genes/
A Tree file = Dibamidae_Hele_Dicro_A_Tree.nwk
B Tree file = Dibamidae_Hele_Dicro_B_Tree.nwk
Phy file location = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/765_gene_sequences_all/
Root of phy file = geneAR_765phyl_
Output gene folder location (Split Genes) = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/split_genes
Root output gene folder = 765phyl_Gene_
Number of genes = 448
Skipped genes = 146 412
Outfile name A tree = aaa
Outfile name B tree = bbb
Mao file path = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/MEGA-X_ov_mean_mcl.mao
Ingroup to tip distance A tree = .3612
Ingroup to tip distance B tree = .294
Root age = .4546
Calibration tree directory A = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/Calibration_Trees/Tree_A/DHD_A_Tree_3Cali_Zero_Balanced.nwk
Calibration tree directory B = /mnt/gs18/scratch/users/u5g6jsxd/Scratch_GS18/mcmctreeProject/master_script/Calibration_Trees/Tree_B/DHD_B_Tree_3Cali_Orig.nwk